### ISSUE TITLE
Start and Stop twice make program panic

### ISSUE THREAD

**Issue by jtbonhomme** [gosuri/uiprogress#40]
Hello,
I may be missing a point, but it seems that starting and stoping a uiprogress twice make the program panic.

Please find bellow a short test program:

```go
package main

import (
    "fmt"
    "time"

    "github.com/gosuri/uiprogress"
)

func createbar() {
    uiprogress.Start()
    defer uiprogress.Stop()
    // create a new bar and prepend the task progress to the bar
    count := 100
    bar := uiprogress.AddBar(count).AppendCompleted().PrependElapsed()
    bar.PrependFunc(func(b *uiprogress.Bar) string {
        return fmt.Sprintf("Task (%d/%d)", b.Current(), count)
    })

    for i := 0; i < count; i++ {
            bar.Incr()
            time.Sleep(time.Millisecond * time.Duration(50))
    }
    time.Sleep(time.Millisecond * time.Duration(500))
}

func main() {
  createbar()
  createbar()
}
```

The console:
```sh
$ go run main.go
Task (100/100)    5s [====================================================================] 100%
Task (1/100)    0s [--------------------------------------------------------------------]   1%
panic: close of closed channel

goroutine 20 [running]:
github.com/gosuri/uiprogress.(*Progress).Listen(0xc00007a1e0)
	/Users/jtbonhomme/Developments/golang/src/github.com/gosuri/uiprogress/progress.go:117 +0x12f
created by github.com/gosuri/uiprogress.(*Progress).Start
	/Users/jtbonhomme/Developments/golang/src/github.com/gosuri/uiprogress/progress.go:134 +0x3f
exit status 2
```

**Comment by jtbonhomme** [comment]
It seems that calling `uiprogress.Stop()` as I did in my program closes the channel (`tdone`) used during the `Listen()` function.

Defer the `Stop()` call solves the problem:
```go
package main

import (
    "fmt"
    "time"

    "github.com/gosuri/uiprogress"
)

func createbar() {
    // create a new bar and prepend the task progress to the bar
    count := 100
    bar := uiprogress.AddBar(count).AppendCompleted().PrependElapsed()
    bar.PrependFunc(func(b *uiprogress.Bar) string {
        return fmt.Sprintf("Task (%d/%d)", b.Current(), count)
    })

    uiprogress.Start()

    for i := 0; i < count; i++ {
            bar.Incr()
            time.Sleep(time.Millisecond * time.Duration(50))
    }
    time.Sleep(time.Millisecond * time.Duration(500))
}

func main() {
  defer uiprogress.Stop()

  createbar()
  createbar()
}
```

This issue can be solved.

**Comment by danlamanna** [comment]
I'm also experiencing this issue.

**Comment by Che4ter** [comment]
I have the same issue..

**Comment by ubiuser** [comment]
I don't think this is a bug, but it definitely needs an example to document this use case for clarity.

**Here is what's happening:**
`uiprogress.Start()` and `uiprogress.Stop()` are using `defaultProgress` which is initialised with `New()`, thus `defaultProgress` is a `Progress` object that has a `tdone` channel. In Go, once a channel is closed (calling `Stop()` in this case) it cannot be reopened or closed again.

**Solution:**
A new Progress instance must be created with New and call Start/Stop on this object.

```
package main

import (
    "fmt"
    "time"

    "github.com/gosuri/uiprogress"
)

func createbar() {
    uip := uiprogress.New()
    uip.Start()
    defer uip.Stop()
    // create a new bar and prepend the task progress to the bar
    count := 100
    bar := uip.AddBar(count).AppendCompleted().PrependElapsed()
    bar.PrependFunc(func(b *uiprogress.Bar) string {
        return fmt.Sprintf("Task (%d/%d)", b.Current(), count)
    })

    for i := 0; i < count; i++ {
        bar.Incr()
        time.Sleep(time.Millisecond * time.Duration(50))
    }
    time.Sleep(time.Millisecond * time.Duration(500))
}

func main() {
    createbar()
    createbar()
}
```

**Comment by kahlys** [comment]
We could create a method `Reset()`, something like this

```go
func Reset() {
	defaultProgress.Stop()
	defaultProgress = New()
}
```
